SkiProductsWebApp/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SkiProductsWebApp.Models;

namespace SkiProductsWebApp.Controllers
{
    public class ProductsController : Controller
    {
        private SkiProductsEntities1 db = new SkiProductsEntities1();
        MvcApplication mvc = new MvcApplication();

        // GET: Products
        //[CustomFilter]
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }

        // GET: Products
        public ActionResult Skiing()
        {
            return View(db.Products.ToList());
        }


        // GET: Products
        public ActionResult Undercap()
        {
            var temp = db.Products.Where(i => i.Category_id == 4).Select(i => i).ToList();
            return View("Skiing", temp);
        }


        // GET: Products
        public ActionResult Skiis()
        {
            var temp = db.Products.Where(i => i.Category_id == 1).Select(i => i).ToList();
            return View("Skiing", temp);
        }

        // GET: Products
        public ActionResult SkiJacket()
        {
            var temp = db.Products.Where(i => i.Category_id == 2).Select(i => i).ToList();
            return View("Skiing", temp);
        }

        // POST: Order
        [HttpPost]
        public ActionResult Order(int product_id)
        {
            if (Session["role"]==null)
            {
                return View("Message");
            }
            //pooveriti da li postoji vec neka porudzbina za korisnika, ako postoji uzeti isti order_num
            //int? onum1 = db.Orders.Select(i => i.Order_num).Last();
            //int? onum2 = db.Orders.Select(i => i.Order_num).Last();
            //dozvoljavam svima koji imaju neku rolu da naprave porudzbinu
            Order order = new Order();
            //string prm = Session["userid"].ToString();
            int userid = Convert.ToInt32(Session["userid"]);
            order.Person_id = userid;
            order.Product_id = product_id;
            order.Order_num = 1;
            try
            {
                db.Orders.Add(order);
                db.SaveChanges();
            }
            catch (Exception)
            {

                throw;
            }
            string url = string.Format("/Products/Cart", userid);
            return Redirect(url);
            //return View("Cart");
        }


        // GET: BrandFilter
        [HttpPost]
        public ActionResult Brand(int brand_id)
        {
            var temp = db.Products.Where(i => i.Brand_id == brand_id).Select(i => i).ToList();
            return View("Skiing", temp);
        }


        // GET: Cart
        //int user_id
        [HttpGet]
        public ActionResult Cart()
        {
            List<Product2> products = new List<Product2>();
            if (Session["userid"] == null)
            {
                return View("Message");
            }
            int uid = Convert.ToInt32(Session["userid"]);
            var chart = db.Orders.Where(i => i.Person_id == uid).Select(i=>i).ToList();

            decimal? price=0;
            foreach (var obj in chart)
            {
                Product2 p = new Product2();
                var temp= db.Products.Where(i => i.Id == obj.Product_id).Select(i => i).First();
                p.Id = temp.Id;
                p.Name = temp.Name;
                p.Price = temp.Price;
                p.Image = temp.Image;
                p.Order_id = obj.Order_id;
                products.Add(p);
                price = price + p.Price;
            }
            ViewBag.TotalPrice=price;
            return View(products);
        }


        // POST: Products/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteOrder(int order_id)
        {
            Order order = db.Orders.Find(order_id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Cart");
        }



        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Price,Image,Description")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Products/Edit/5
        //[Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Price,Image,Description")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SkiProductsWebApp/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SkiProductsWebApp.Models;

namespace SkiProductsWebApp.Controllers
{
    public class UsersController : Controller
    {
        private SkiProductsEntities1 db = new SkiProductsEntities1();
        MvcApplication mvc = new MvcApplication();


        // GET: Users
        public ActionResult Index()
        {
            
            return View(db.Users.ToList());
        }
        // GET: Users/Login
        [HttpGet]
        public ActionResult Login()
        {
           
            return View();
        }

        // POST: Users/Authentication
        [HttpPost]
        public ActionResult Authentication(string username, string pwd)
        {
            bool param=false;
            var obj=db.Users.Where(i => i.Username == username).Select(i=>i).First();
            if (obj.Password.Trim()==pwd)
            {
                param = true;
            }
            if (obj!=null && param==true)
            {
                mvc.Session_Start(obj.Role_id.ToString(), obj.Id.ToString());
                return View("~/Views/Home/Index.cshtml");
            }
            return View("Login");
        }


        // GET: Users/Logout
        [HttpGet]
        public ActionResult Logout()
        {
            //Session.Remove("ss");
            mvc.Session_End();

            return View("Login");
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Username,Password,Email")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Username,Password,Email")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SkiProductsWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!--Font awesome icons below-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ski shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("Proizvodi", "Skiing", "Products")</li>
                    <li>@Html.ActionLink("Korpa", "Cart", "Products")</li>
                    <li>@Html.ActionLink("O nama", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    @*<i class="fas fa-shopping-cart" style="color:white; padding:17px;"></i>*@
                    @if ((string)Session["role"] == "1")
                    {
                        <li><i class="far fa-edit" style="color:white; padding:17px;">@Html.ActionLink("Proizvodi", "Index", "Products")</i></li>
                        <li><i class="far fa-edit" style="color:white; padding:17px;">@Html.ActionLink("Korisnici", "Index", "Users")</i></li>
                    }

                    @if (Session["role"] != null)
                    {
                        <li>@Html.ActionLink("Logout", "Logout", "Users")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Users")</li>
                    }

                    @*<li>
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                    Dropdown Example
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li><a href="#">HTML</a></li>
                    <li><a href="#">CSS</a></li>
                    <li><a href="#">JavaScript</a></li>
                </ul>
            </div>
        </li>*@
                </ul>
                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>